'use strict';
const $=s=>document.querySelector(s),KEY='camino-v1';
const SHOP=[{id:'forest',kind:'theme',name:'青柠',price:0,icon:'🍃'},{id:'ocean',kind:'theme',name:'海盐蓝',price:120,icon:'🌊'},{id:'peach',kind:'theme',name:'日落桃',price:220,icon:'🍑'},{id:'night',kind:'theme',name:'星夜',price:350,icon:'🌙'},{id:'sprout',kind:'pet',name:'小芽',price:0,icon:'🌱'},{id:'cactus',kind:'pet',name:'仙人掌',price:100,icon:'🌵'},{id:'fox',kind:'pet',name:'小狐狸',price:180,icon:'🦊'},{id:'owl',kind:'pet',name:'小猫头鹰',price:260,icon:'🦉'},{id:'plain',kind:'frame',name:'简洁',price:0,icon:'○'},{id:'stars',kind:'frame',name:'星星边框',price:160,icon:'✦'},{id:'rainbow',kind:'frame',name:'彩虹边框',price:280,icon:'🌈'}];
const fresh=()=>({version:2,xp:0,spent:0,owned:['forest','sprout','plain'],equipped:{theme:'forest',pet:'sprout',frame:'plain'},done:{},read:{},records:{},sections:{},last:'start',dictionary:true,daily:{}});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lessonById=id=>LESSONS.find(l=>l.id===id),balance=()=>Math.max(0,state.xp-state.spent);
const today=()=>{const d=new Date();return `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`};
function migrate(s){if(s.version===1)return {...fresh(),xp:s.xp,done:s.done,read:s.read,records:s.records,last:lessonById(s.last)?s.last:'start'};return{...fresh(),...s,version:2,equipped:{...fresh().equipped,...s.equipped}}}
function validBackup(s){if(!s||![1,2].includes(s.version)||!Number.isSafeInteger(s.xp)||s.xp<0||s.xp>1e9)return false;for(const k of ['done','read','records'])if(!s[k]||typeof s[k]!=='object'||Array.isArray(s[k]))return false;const ids=new Set(BANK.map(q=>q.id));if(!Object.entries(s.records).every(([id,r])=>ids.has(id)&&r&&Number.isInteger(r.attempts)&&r.attempts>=0&&Number.isInteger(r.streak)&&r.streak>=0&&Number.isFinite(r.due)&&typeof r.wrong==='boolean'))return false;if(!['done','read'].every(k=>Object.entries(s[k]).every(([id,v])=>lessonById(id)&&typeof v==='boolean')))return false;if(s.version===2){if(!Number.isSafeInteger(s.spent)||s.spent<0||s.spent>s.xp||!Array.isArray(s.owned)||new Set(s.owned).size!==s.owned.length||!s.owned.every(id=>SHOP.some(x=>x.id===id)))return false;if(!s.equipped||!['theme','pet','frame'].every(k=>SHOP.some(x=>x.id===s.equipped[k]&&x.kind===k)&&s.owned.includes(s.equipped[k])))return false;if(s.spent!==SHOP.filter(x=>s.owned.includes(x.id)).reduce((n,x)=>n+x.price,0))return false;if(typeof s.dictionary!=='boolean'||!s.sections||typeof s.sections!=='object'||!s.daily||typeof s.daily!=='object')return false;if(!Object.entries(s.sections).every(([id,n])=>lessonById(id)&&Number.isInteger(n)&&n>=0&&n<lessonById(id).blocks.length))return false;if(!Object.entries(s.daily).every(([d,n])=>/^\d{4}-\d{1,2}-\d{1,2}$/.test(d)&&Number.isSafeInteger(n)&&n>=0))return false}return true}
let state=fresh(),storageOK=true;
try{const s=JSON.parse(localStorage.getItem(KEY));if(s){if(validBackup(s))state=migrate(s);else storageOK=false}}catch(e){storageOK=false}
let view='home',session=null,filter='全部',search='',currentLesson='start',currentSection=0;
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true}catch(e){storageOK=false}updateHeader()}
function updateHeader(){$('#xp').textContent=`✦ ${balance()}`;$('#xp').setAttribute('aria-label',`可兑换 ${balance()} 经验值`);$('#saveState').textContent=storageOK?'':'保存失败，请导出';document.body.dataset.theme=state.equipped.theme;document.body.dataset.frame=state.equipped.frame}
function toast(t){$('#toast').textContent=t;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,2600)}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function normalized(s){return String(s).normalize('NFC').trim().toLowerCase().replace(/[¿?¡!.,;:]+$/g,'').replace(/^[¿¡]+/g,'').replace(/\s+/g,' ')}
function correct(a,b){return b.split('/').some(x=>normalized(x)===normalized(a))}
function due(){return BANK.filter(q=>state.records[q.id]?.due<=Date.now())}
function wrong(){return BANK.filter(q=>state.records[q.id]?.wrong)}
function pet(){return SHOP.find(x=>x.id===state.equipped.pet)?.icon||'🌱'}
function rich(s){return String(s??'').split(/([A-Za-zÁÉÍÓÚÜÑáéíóúüñ]+)/g).map((p,i)=>i%2?`<span class="word" data-word="${esc(p)}" tabindex="0">${esc(p)}</span>`:esc(p)).join('').replace(/\n/g,'<br>')}
function header(title,sub=''){return `<div class="page-title"><h1>${title}</h1>${sub?`<span class="muted">${sub}</span>`:''}</div>`}
function go(v){hideTip();view=v;session=null;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));render();window.scrollTo(0,0)}
function render(){updateHeader();$('#app').innerHTML=({home,library,lab,review,map,shop,settings}[view]||home)();$('#app').className='fade'}
function home(){const done=Object.keys(state.done).length,next=LESSONS.find(l=>!state.done[l.id])||LESSONS[0];return `${header('学习',`${done} / ${LESSONS.length}`)}<section class="continue-card"><div class="avatar ${state.equipped.frame}">${pet()}</div><div><small>${next.group}</small><h2>${next.title}</h2><button class="primary" data-lesson="${next.id}">${state.read[next.id]?'继续':'学习'} →</button></div></section><div class="mini-stats"><span>◉ 今日 ${state.daily[today()]||0} 题</span><button data-view="review">↺ ${due().length} 题待复习</button><button data-view="shop">✦ ${balance()} XP</button></div><div class="path">${LESSONS.map((l,i)=>`${i===0||LESSONS[i-1].group!==l.group?`<div class="path-section"><span>${l.group}</span></div>`:''}<div class="path-item ${state.done[l.id]?'done':''}"><button class="path-node ${l.id===next.id?'next':''}" data-lesson="${l.id}" aria-label="${esc(l.title)}">${state.done[l.id]?'✓':i+1}</button><div><button class="lesson-title" data-lesson="${l.id}">${l.title}</button><small>${state.done[l.id]?'已通过':state.read[l.id]?'已读':''}</small></div></div>`).join('')}</div>`}
function row(l){return `<button class="lesson-row" data-lesson="${l.id}"><span class="row-icon">${state.done[l.id]?'✓':'▤'}</span><span><b>${l.title}</b><small>${l.group}</small></span><span>›</span></button>`}
function results(){const term=normalized(search),ls=LESSONS.filter(l=>(filter==='全部'||l.group===filter)&&normalized(l.title+l.blocks.map(b=>b.title+b.text).join('')+COVERAGE.filter(c=>c[1]===l.id).map(c=>c[0]).join('')).includes(term));return ls.length?ls.map(row).join(''):'<div class="empty">没有找到</div>'}
function library(){return `${header('语法')}<input id="search" class="search" type="search" value="${esc(search)}" placeholder="搜索知识点" aria-label="搜索知识点"><div class="chips">${['全部',...new Set(LESSONS.map(l=>l.group))].map(g=>`<button class="chip ${filter===g?'active':''}" data-filter="${g}">${g}</button>`).join('')}</div><div class="catalog" id="results">${results()}</div><button class="text-button" data-view="map">全部知识点 ↗</button>`}
function showLesson(id,section){const l=lessonById(id);if(!l)return;hideTip();view='lesson';session=null;currentLesson=id;currentSection=Math.max(0,Math.min(l.blocks.length-1,section??state.sections[id]??0));state.last=id;state.sections[id]=currentSection;save();const b=l.blocks[currentSection];$('#app').innerHTML=`<article class="reading fade"><div class="lesson-top"><button class="icon-button" data-view="home" aria-label="返回">←</button><div class="bar"><span style="width:${(currentSection+1)/l.blocks.length*100}%"></span></div><span>${currentSection+1}/${l.blocks.length}</span></div><div class="lesson-label">${l.title}</div><div class="section-selector"><select id="sectionSelect" aria-label="讲解章节">${l.blocks.map((b,i)=>`<option value="${i}" ${i===currentSection?'selected':''}>${i+1}. ${b.title}</option>`).join('')}</select><button class="text-button" data-practice="${id}">练习</button></div><section class="reading-card"><h1>${b.title}</h1><div class="prose">${rich(b.text)}</div>${b.example?`<div class="example"><b>${rich(b.example)}</b><p>${esc(b.translation)}</p></div>`:''}${b.warning?`<div class="warning">${rich(b.warning)}</div>`:''}</section>${l.tenses.length?`<details class="table-detail"><summary>变位表</summary><select id="lessonVerb" aria-label="动词">${verbOptions('hablar')}</select><div id="lessonTables">${l.tenses.map(t=>table('hablar',t)).join('')}</div></details>`:''}<div class="reading-actions"><button class="secondary" data-section="${currentSection-1}" ${currentSection===0?'disabled':''}>上一节</button><button class="primary" ${currentSection===l.blocks.length-1?`data-complete="${id}"`:`data-section="${currentSection+1}"`}>${currentSection===l.blocks.length-1?'开始练习':'继续'} →</button></div></article>`;window.scrollTo(0,0)}
function verbOptions(v){return Object.keys(VERBS).map(x=>`<option value="${x}" ${x===v?'selected':''}>${x} · ${VERBS[x].meaning}</option>`).join('')}
function table(v,t){return `<h3>${TENSES[t]}</h3><div class="table-wrap"><table><tbody>${forms(v,t).map((a,i)=>`<tr><th>${PEOPLE[i]}</th><td>${rich(a)}</td></tr>`).join('')}</tbody></table></div>`}
function lab(){return `${header('变位')}<div class="controls"><select id="labVerb" aria-label="动词">${verbOptions('tener')}</select><select id="labTense" aria-label="时态">${Object.keys(TENSES).map(t=>`<option value="${t}">${TENSES[t]}</option>`).join('')}</select><button class="primary" id="labTrain">练习</button></div><section class="card" id="labTable">${table('tener','present')}</section><div class="card" id="nonfinite">${nonfinite('tener')}</div>`}
function nonfinite(v){return `<div class="forms-row"><span>原形<br><b>${rich(v)}</b></span><span>副动词<br><b>${rich(gerund(v))}</b></span><span>过去分词<br><b>${rich(participle(v))}</b></span></div>`}
function review(){const w=wrong(),d=due();return `${header('复习')}<div class="review-grid"><button class="review-card" data-session="due" ${d.length?'':'disabled'}><span>↺</span><h2>到期复习</h2><b>${d.length}</b></button><button class="review-card" data-session="wrong" ${w.length?'':'disabled'}><span>✎</span><h2>错题</h2><b>${w.length}</b></button><button class="review-card" data-session="mixed"><span>⤨</span><h2>混合练习</h2><small>已学课程</small></button></div>${w.length?`<h2 class="space">错题本</h2>${w.map(q=>`<details class="card"><summary>${esc(q.prompt)}</summary><p class="answer-line">${rich(q.answer.replaceAll('/',' / '))}</p><p>${rich(q.explain)}</p><button class="text-button" data-lesson="${q.lesson}">相关语法 →</button></details>`).join('')}`:'<div class="empty">暂无错题</div>'}`}
function map(){return `${header('知识索引',`${COVERAGE.length} 项`)}<div class="catalog">${COVERAGE.map(([name,id])=>`<button class="lesson-row" data-lesson="${id}"><span class="row-icon">${state.done[id]?'✓':'·'}</span><b>${name}</b><span>›</span></button>`).join('')}</div>`}
function shop(){return `${header('商店',`✦ ${balance()} XP`)}<p class="muted">新题答对 +10 · 到期复习 +3 · 首次通关 +20</p><div class="closet"><div class="avatar ${state.equipped.frame}">${pet()}</div><span>我的装扮</span></div>${[['theme','主题'],['pet','伙伴'],['frame','边框']].map(([kind,name])=>`<h2 class="space">${name}</h2><div class="shop-grid">${SHOP.filter(x=>x.kind===kind).map(x=>{const owned=state.owned.includes(x.id),active=state.equipped[kind]===x.id;return `<article class="shop-item ${active?'equipped':''}"><div class="item-preview ${kind==='theme'?'swatch '+x.id:kind==='frame'?'frame-preview '+x.id:''}">${x.icon}</div><h3>${x.name}</h3><button class="${owned?'secondary':'primary'}" data-item="${x.id}" ${active||(!owned&&balance()<x.price)?'disabled':''}>${active?'使用中':owned?'使用':`✦ ${x.price}`}</button></article>`}).join('')}</div>`).join('')}`}
function buy(id){const item=SHOP.find(x=>x.id===id);if(!item)return false;if(!state.owned.includes(id)){if(balance()<item.price){toast('经验值不足');return false}state.spent+=item.price;state.owned.push(id)}state.equipped[item.kind]=id;save();if(view==='shop')render();toast('已装备 '+item.name);return true}
function settings(){return `${header('设置')}<div class="card settings-list"><label class="toggle">悬停释义<input id="dictionaryToggle" type="checkbox" ${state.dictionary?'checked':''}></label><a href="https://www.eudic.net/v4/es/app/plugins" target="_blank" rel="noopener noreferrer">西语助手官方插件 ↗</a><small class="muted">官方划词释义需插件；本地网页需开启插件的“允许访问文件网址”。悬停卡片中的“本地释义”为内置词义。</small></div><div class="card settings-list"><button class="secondary" id="export">导出进度</button><button class="secondary" id="import">导入进度</button><small class="muted">本机保存。换浏览器前请备份。</small></div><details class="card"><summary>参考资料</summary>${SOURCES.map(([t,u])=>`<p><a href="${u}" target="_blank" rel="noopener noreferrer">${t} ↗</a></p>`).join('')}<p><a href="https://www.rae.es/diccionario-estudiante/docs/numerales.pdf" target="_blank" rel="noopener noreferrer">RAE：数词 ↗</a></p></details>`}
function startLesson(id){const l=lessonById(id),curated=shuffle(l.qs),drills=shuffle(BANK.filter(q=>q.lesson===id&&!l.qs.some(x=>x.id===q.id))),n=Math.min(8,curated.length);start([...curated.slice(0,n),...drills.slice(0,Math.max(0,10-n))],l.title,id)}
function start(qs,title,lesson=null){hideTip();if(!qs.length){toast('暂无题目，请先学习一课');return}view='quiz';session={qs:shuffle(qs),index:0,correct:0,title,lesson,checked:false,selected:null,results:[],earned:0,finished:false};drawQuiz();window.scrollTo(0,0)}
function drawQuiz(){const s=session,q=s.qs[s.index];if(!q){finish();return}s.checked=false;s.selected=null;$('#app').innerHTML=`<div class="quiz fade"><div class="lesson-top"><button class="icon-button" id="quitQuiz" aria-label="退出练习">×</button><div class="bar"><span style="width:${s.index/s.qs.length*100}%"></span></div><span>${s.index+1}/${s.qs.length}</span></div><small class="lesson-label">${esc(s.title)}</small><div class="question">${rich(q.prompt)}</div>${q.options?`<div class="options">${shuffle(q.options).map((o,i)=>`<button class="option" data-option="${esc(o)}"><span class="option-number">${i+1}</span><span>${rich(o)}</span></button>`).join('')}</div>`:`<input class="answer-input" id="answer" aria-label="答案" placeholder="输入答案" autocomplete="off" autocapitalize="off" spellcheck="false"><div class="keyboard">${'á é í ó ú ü ñ'.split(' ').map(c=>`<button data-char="${c}" aria-label="输入 ${c}">${c}</button>`).join('')}</div>`}<div id="feedback" aria-live="polite"></div><div class="quiz-actions"><button class="text-button" id="reveal">暂时不会</button><button class="primary" id="check">检查</button></div></div>`;$('#answer')?.focus()}
function check(reveal=false){const s=session;if(!s||s.checked)return;const q=s.qs[s.index],a=q.options?s.selected:$('#answer').value;if(!reveal&&!a?.trim()){toast('请作答');return}hideTip();s.checked=true;const ok=!reveal&&correct(a,q.answer);if(ok)s.correct++;s.results.push({q,ok,a:a||'—'});const old=state.records[q.id]||{attempts:0,streak:0},streak=ok?old.streak+1:0,gain=ok?(old.attempts===0?10:old.due<=Date.now()?3:0):0;state.records[q.id]={attempts:old.attempts+1,streak,wrong:!ok,due:Date.now()+(ok?[1,3,7,14,30][Math.min(streak-1,4)]*86400000:600000)};state.xp+=gain;s.earned+=gain;state.daily[today()]=(state.daily[today()]||0)+1;save();$('#feedback').innerHTML=`<div class="feedback ${ok?'':'wrong'}"><h3>${ok?'✓ 正确':'正确答案'}</h3>${ok?'':`<p class="answer-line">${rich(q.answer.replaceAll('/',' / '))}</p>`}<p>${rich(q.explain)}</p>${gain?`<span class="reward">+${gain} XP</span>`:''}</div>`;document.querySelectorAll('.option,#answer,.keyboard button').forEach(el=>el.disabled=true);$('#check').id='next';$('#next').textContent=s.index===s.qs.length-1?'完成':'继续';$('#reveal').hidden=true;$('#next').focus()}
function finish(){const s=session;if(!s)return;const score=Math.round(s.correct/s.qs.length*100),pass=score>=80;if(!s.finished){if(s.lesson&&pass&&!state.done[s.lesson]){state.done[s.lesson]=true;state.xp+=20;s.earned+=20}save();s.finished=true}$('#app').innerHTML=`<div class="quiz"><div class="result-card"><div class="avatar ${state.equipped.frame}">${pet()}</div><h1>${pass?'完成！':'再练一次'}</h1><div class="result-stats"><div><b>${score}%</b><small>正确率</small></div><div><b>+${s.earned}</b><small>XP</small></div></div><p>${s.correct} / ${s.qs.length}${s.lesson&&!pass?' · 80% 通过':''}</p><button class="primary" data-view="home">继续学习</button><button class="text-button" id="retry">再练一轮</button></div>${s.results.filter(r=>!r.ok).map(r=>`<div class="card"><p>${rich(r.q.prompt)}</p><p class="answer-line">${rich(r.q.answer)}</p><p>${rich(r.q.explain)}</p><button class="text-button" data-lesson="${r.q.lesson}">语法 →</button></div>`).join('')}</div>`}
function exportProgress(){const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='Camino-进度-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已导出')}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.view)return go(b.dataset.view);if(b.dataset.lesson)return showLesson(b.dataset.lesson);if(b.dataset.practice)return startLesson(b.dataset.practice);if(b.dataset.complete){state.read[b.dataset.complete]=true;save();return startLesson(b.dataset.complete)}if(b.dataset.section!==undefined)return showLesson(currentLesson,Number(b.dataset.section));if(b.dataset.filter){filter=b.dataset.filter;return render()}if(b.dataset.item)return buy(b.dataset.item);if(b.dataset.option){if(session?.checked)return;session.selected=b.dataset.option;document.querySelectorAll('.option').forEach(o=>o.classList.toggle('selected',o===b));return}if(b.dataset.char){const a=$('#answer');if(a&&!a.disabled){const i=a.selectionStart,j=a.selectionEnd;a.value=a.value.slice(0,i)+b.dataset.char+a.value.slice(j);a.focus();a.setSelectionRange(i+1,i+1)}return}if(b.dataset.session){const mode=b.dataset.session,qs=mode==='due'?due():mode==='wrong'?wrong():BANK.filter(q=>state.read[q.lesson]||state.done[q.lesson]||state.records[q.id]);return start(shuffle(qs).slice(0,10),mode==='due'?'到期复习':mode==='wrong'?'错题':'混合练习')}switch(b.id){case'check':check();break;case'reveal':check(true);break;case'next':session.index++;drawQuiz();break;case'quitQuiz':go('review');break;case'retry':{const s=session;s.lesson?startLesson(s.lesson):start(s.qs,s.title);break}case'export':exportProgress();break;case'import':$('#file').click();break;case'labTrain':{const v=$('#labVerb').value,t=$('#labTense').value,l=LESSONS.find(l=>l.id!=='start'&&l.tenses.includes(t));start(BANK.filter(q=>q.id.startsWith(`${l.id}-${t}-${v}-`)),`${v} · ${TENSES[t]}`);break}}});
document.addEventListener('input',e=>{if(e.target.id==='search'){search=e.target.value;$('#results').innerHTML=results()}});
document.addEventListener('change',e=>{if(['labVerb','labTense'].includes(e.target.id)){const v=$('#labVerb').value;$('#labTable').innerHTML=table(v,$('#labTense').value);$('#nonfinite').innerHTML=nonfinite(v)}if(e.target.id==='lessonVerb')$('#lessonTables').innerHTML=lessonById(currentLesson).tenses.map(t=>table(e.target.value,t)).join('');if(e.target.id==='sectionSelect')showLesson(currentLesson,Number(e.target.value));if(e.target.id==='dictionaryToggle'){state.dictionary=e.target.checked;hideTip();save()}});
document.addEventListener('keydown',e=>{if(e.key==='Escape')hideTip();if(e.key==='Enter'&&view==='quiz'&&session&&!e.target.closest('button,a,.word,select')){if($('#next'))$('#next').click();else if($('#check'))check()}});
$('#file').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>5000000)throw Error();const s=JSON.parse(await f.text());if(!validBackup(s))throw Error();if(!confirm('用备份替换当前进度和装扮？'))return;state=migrate(s);save();go('home');toast('已恢复')}catch(e){toast('备份格式不正确，未修改进度')}finally{$('#file').value=''}});
document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();go('home')});
let tipTimer,tipClose,tipWord;
function hideTip(){clearTimeout(tipTimer);clearTimeout(tipClose);$('#wordTip').hidden=true;tipWord=null}
function showTip(el){if(!state.dictionary||!el?.isConnected)return;const word=el.dataset.word,entry=lookup(word);tipWord=el;const tip=$('#wordTip');tip.innerHTML=`<div class="tip-head"><b>${esc(word)}</b><button class="tip-close" aria-label="关闭释义">×</button></div>${entry?`<p>${esc(entry)}</p><small>本地释义</small>`:'<small>暂无本地释义</small>'}<a href="https://www.esdict.cn/dicts/es/${encodeURIComponent(word.toLowerCase())}" target="_blank" rel="noopener noreferrer">西语助手查词 ↗</a>`;tip.hidden=false;const r=el.getBoundingClientRect(),w=Math.min(300,window.innerWidth-24);tip.style.width=w+'px';tip.style.left=Math.max(12,Math.min(r.left,window.innerWidth-w-12))+'px';const h=tip.offsetHeight;tip.style.top=(r.bottom+h+14<window.innerHeight?r.bottom+9:Math.max(10,r.top-h-9))+'px'}
document.addEventListener('pointerover',e=>{const w=e.target.closest('.word');if(w&&state.dictionary){clearTimeout(tipClose);if(w!==tipWord){clearTimeout(tipTimer);tipTimer=setTimeout(()=>showTip(w),350)}}if(e.target.closest('#wordTip'))clearTimeout(tipClose)});
document.addEventListener('pointerout',e=>{if(e.target.closest('.word')||e.target.closest('#wordTip')){clearTimeout(tipTimer);clearTimeout(tipClose);tipClose=setTimeout(hideTip,220)}});
document.addEventListener('focusin',e=>{if(e.target.matches('.word'))showTip(e.target)});
document.addEventListener('click',e=>{if(e.target.closest('.tip-close'))hideTip();else if(e.target.closest('.word')&&!e.target.closest('button'))showTip(e.target.closest('.word'));else if(!e.target.closest('#wordTip'))hideTip()});
document.addEventListener('scroll',hideTip,{passive:true,capture:true});
go('home');
