'use strict';
const $=s=>document.querySelector(s),KEY='camino-v1';
const SHOP=[{id:'forest',kind:'theme',name:'青柠',price:0,icon:'🍃'},{id:'ocean',kind:'theme',name:'海盐蓝',price:120,icon:'🌊'},{id:'peach',kind:'theme',name:'日落桃',price:220,icon:'🍑'},{id:'night',kind:'theme',name:'星夜',price:350,icon:'🌙'},{id:'sprout',kind:'pet',name:'奶油兔',price:0,icon:'🌱'},{id:'cactus',kind:'pet',name:'小海龟',price:100,icon:'🌵'},{id:'fox',kind:'pet',name:'小狐狸',price:180,icon:'🦊'},{id:'owl',kind:'pet',name:'小猫头鹰',price:260,icon:'🦉'},{id:'plain',kind:'frame',name:'简洁',price:0,icon:'○'},{id:'stars',kind:'frame',name:'星星边框',price:160,icon:'✦'},{id:'rainbow',kind:'frame',name:'彩虹边框',price:280,icon:'🌈'}];
SHOP.push(...[{"id":"lavender","kind":"theme","name":"薰衣草","price":650,"icon":"🪻"},{"id":"rose","kind":"theme","name":"莓果奶昔","price":800,"icon":"🍓"},{"id":"sand","kind":"theme","name":"暖沙","price":900,"icon":"🏜️"},{"id":"mint","kind":"theme","name":"薄荷汽水","price":1000,"icon":"🫧"},{"id":"axolotl","kind":"pet","name":"桃桃螈","price":800,"icon":"🩷"},{"id":"penguin","kind":"pet","name":"小企鹅","price":950,"icon":"🐧"},{"id":"dragon","kind":"pet","name":"紫龙","price":1400,"icon":"🐉"},{"id":"cloud","kind":"pet","name":"小海豹","price":1600,"icon":"☁️"},{"id":"cat","kind":"pet","name":"奶油猫","price":850,"icon":"🐱"},{"id":"whale","kind":"pet","name":"蓝鲸","price":1100,"icon":"🐳"},{"id":"mushroom","kind":"pet","name":"竹竹熊猫","price":1250,"icon":"🍄"},{"id":"robot","kind":"pet","name":"布丁犬","price":1800,"icon":"🤖"},{"id":"gold","kind":"frame","name":"金色徽章","price":1000,"icon":"✧"},{"id":"orbit","kind":"frame","name":"星球轨道","price":1300,"icon":"🪐"},{"id":"petals","kind":"frame","name":"花瓣环","price":850,"icon":"🌸"},{"id":"none","kind":"hat","name":"原装","price":0,"icon":"—"},{"id":"beret","kind":"hat","name":"画家帽","price":600,"icon":"🎨"},{"id":"bow","kind":"hat","name":"蝴蝶结","price":700,"icon":"🎀"},{"id":"explorer","kind":"hat","name":"探险帽","price":950,"icon":"🧭"},{"id":"glasses","kind":"hat","name":"读书眼镜","price":750,"icon":"👓"},{"id":"crown","kind":"hat","name":"王冠","price":2200,"icon":"👑"},{"id":"meadow","kind":"scene","name":"草地","price":0,"icon":"🌿"},{"id":"starscape","kind":"scene","name":"星空课堂","price":1400,"icon":"🌌"},{"id":"confetti","kind":"scene","name":"彩纸课堂","price":1200,"icon":"🎊"},{"id":"bubbles","kind":"scene","name":"泡泡课堂","price":1100,"icon":"🫧"}]);
const fresh=()=>({version:3,vocab:{},rounds:{},setWins:{},rewardDays:{},xp:0,spent:0,owned:['forest','sprout','plain','none','meadow'],equipped:{theme:'forest',pet:'sprout',frame:'plain',hat:'none',scene:'meadow'},done:{},read:{},records:{},sections:{},last:'start',dictionary:true,daily:{}});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lessonById=id=>LESSONS.find(l=>l.id===id),balance=()=>Math.max(0,state.xp-state.spent);
const today=()=>{const d=new Date();return `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`};
function migrate(s){if(s.version===1)return {...fresh(),xp:s.xp,done:s.done,read:s.read,records:s.records,last:lessonById(s.last)?s.last:'start'};return{...fresh(),...s,version:3,owned:[...new Set([...(s.owned||[]),'none','meadow'])],equipped:{...fresh().equipped,...s.equipped}}}
function validBackup(s){if(!s||![1,2,3].includes(s.version)||!Number.isSafeInteger(s.xp)||s.xp<0||s.xp>1e9)return false;for(const k of ['done','read','records'])if(!s[k]||typeof s[k]!=='object'||Array.isArray(s[k]))return false;const ids=new Set(BANK.map(q=>q.id));if(!Object.entries(s.records).every(([id,r])=>ids.has(id)&&r&&Number.isInteger(r.attempts)&&r.attempts>=0&&Number.isInteger(r.streak)&&r.streak>=0&&Number.isFinite(r.due)&&typeof r.wrong==='boolean'))return false;if(!['done','read'].every(k=>Object.entries(s[k]).every(([id,v])=>lessonById(id)&&typeof v==='boolean')))return false;if(s.version>=2){if(!Number.isSafeInteger(s.spent)||s.spent<0||s.spent>s.xp||!Array.isArray(s.owned)||new Set(s.owned).size!==s.owned.length||!s.owned.every(id=>SHOP.some(x=>x.id===id)))return false;if(!s.equipped||!['theme','pet','frame'].every(k=>SHOP.some(x=>x.id===s.equipped[k]&&x.kind===k)&&s.owned.includes(s.equipped[k])))return false;if(s.spent!==SHOP.filter(x=>s.owned.includes(x.id)).reduce((n,x)=>n+x.price,0))return false;if(typeof s.dictionary!=='boolean'||!s.sections||typeof s.sections!=='object'||!s.daily||typeof s.daily!=='object')return false;if(!Object.entries(s.sections).every(([id,n])=>lessonById(id)&&Number.isInteger(n)&&n>=0&&n<lessonById(id).blocks.length))return false;if(!Object.entries(s.daily).every(([d,n])=>/^\d{4}-\d{1,2}-\d{1,2}$/.test(d)&&Number.isSafeInteger(n)&&n>=0))return false}if(s.version===3&&!validV3(s))return false;return true}
let state=fresh(),storageOK=true;
try{const s=JSON.parse(localStorage.getItem(KEY));if(s){if(validBackup(s))state=migrate(s);else storageOK=false}}catch(e){storageOK=false}
let view='home',session=null,filter='全部',search='',currentLesson='start',currentSection=0;
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true}catch(e){storageOK=false}updateHeader()}
function updateHeader(){$('#xp').textContent=`✦ ${balance()}`;$('#xp').setAttribute('aria-label',`可兑换 ${balance()} 经验值`);$('#saveState').textContent=storageOK?'':'保存失败，请导出';document.body.dataset.theme=state.equipped.theme;document.body.dataset.frame=state.equipped.frame}
function toast(t){$('#toast').textContent=t;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,2600)}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function normalized(s){return String(s).normalize('NFC').trim().toLowerCase().replace(/[¿?¡!.,;:]+$/g,'').replace(/^[¿¡]+/g,'').replace(/\s+/g,' ')}
function correct(a,b){return b.split('/').some(x=>normalized(x)===normalized(a))}
function due(){return BANK.filter(q=>state.records[q.id]?.due<=Date.now())}
function wrong(){return BANK.filter(q=>state.records[q.id]?.wrong)}
function pet(){return mascot('idle',state.equipped.pet)}
function rich(s){return String(s??'').split(/([A-Za-zÁÉÍÓÚÜÑáéíóúüñ]+)/g).map((p,i)=>i%2?`<span class="word" data-word="${esc(p)}" tabindex="0" draggable="false" aria-label="单词：${esc(p)}">${esc(p)}</span>`:esc(p)).join('').replace(/\n/g,'<br>')}
function header(title,sub=''){return `<div class="page-title"><h1>${title}</h1>${sub?`<span class="muted">${sub}</span>`:''}</div>`}
function go(v){hideTip();view=v;session=null;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));render();window.scrollTo(0,0)}
function render(){updateHeader();$('#app').innerHTML=({home,library,lab,review,map,shop,settings,vocabulary}[view]||home)();$('#app').className='fade'}
function home(){const done=Object.keys(state.done).length,next=LESSONS.find(l=>!state.done[l.id])||LESSONS[0];return `${header('学习',`${done} / ${LESSONS.length}`)}<section class="continue-card"><div class="avatar ${state.equipped.frame}">${pet()}</div><div><small>${next.group}</small><h2>${next.title}</h2><button class="primary" data-lesson="${next.id}">${state.read[next.id]?'继续':'学习'} →</button></div></section><div class="mini-stats"><span>◉ 今日 ${state.daily[today()]||0} 题</span><button data-view="review">↺ ${due().length} 题待复习</button><button data-view="shop">✦ ${balance()} XP</button></div><div class="path">${LESSONS.map((l,i)=>`${i===0||LESSONS[i-1].group!==l.group?`<div class="path-section"><span>${l.group}</span></div>`:''}<div class="path-item ${state.done[l.id]?'done':''}"><button class="path-node ${l.id===next.id?'next':''}" data-lesson="${l.id}" aria-label="${esc(l.title)}">${state.done[l.id]?'✓':i+1}</button><div><button class="lesson-title" data-lesson="${l.id}">${l.title}</button><small>${state.done[l.id]?'已通过':state.read[l.id]?'已读':''}</small></div></div>`).join('')}</div>`}
function row(l){return `<button class="lesson-row" data-lesson="${l.id}"><span class="row-icon">${state.done[l.id]?'✓':'▤'}</span><span><b>${l.title}</b><small>${l.group}</small></span><span>›</span></button>`}
function results(){const term=normalized(search),ls=LESSONS.filter(l=>(filter==='全部'||l.group===filter)&&normalized(l.title+l.blocks.map(b=>b.title+b.text).join('')+COVERAGE.filter(c=>c[1]===l.id).map(c=>c[0]).join('')).includes(term));return ls.length?ls.map(row).join(''):'<div class="empty">没有找到</div>'}
function library(){return `${header('语法')}<input id="search" class="search" type="search" value="${esc(search)}" placeholder="搜索知识点" aria-label="搜索知识点"><div class="chips">${['全部',...new Set(LESSONS.map(l=>l.group))].map(g=>`<button class="chip ${filter===g?'active':''}" data-filter="${g}">${g}</button>`).join('')}</div><div class="catalog" id="results">${results()}</div><button class="text-button" data-view="map">全部知识点 ↗</button>`}
function showLesson(id,section){const l=lessonById(id);if(!l)return;hideTip();view='lesson';session=null;currentLesson=id;currentSection=Math.max(0,Math.min(l.blocks.length-1,section??state.sections[id]??0));state.last=id;state.sections[id]=currentSection;save();const b=l.blocks[currentSection];$('#app').innerHTML=`<article class="reading fade"><div class="lesson-top"><button class="icon-button" data-view="home" aria-label="返回">←</button><div class="bar"><span style="width:${(currentSection+1)/l.blocks.length*100}%"></span></div><span>${currentSection+1}/${l.blocks.length}</span></div><div class="lesson-label">${l.title}</div><div class="section-selector"><select id="sectionSelect" aria-label="讲解章节">${l.blocks.map((b,i)=>`<option value="${i}" ${i===currentSection?'selected':''}>${i+1}. ${b.title}</option>`).join('')}</select><button class="text-button" data-practice="${id}">第 ${(state.rounds[id]||0)%4+1} / 4 套 →</button></div><div class="classroom-stage" aria-hidden="true"><span class="chalk-star">✦</span>${mascot('teach')}<span class="chalk-star">✧</span></div><section class="reading-card"><h1>${b.title}</h1><div class="prose">${rich(b.text)}</div>${b.example?`<div class="example"><b>${rich(b.example)}</b><p>${esc(b.translation)}</p></div>`:''}${b.warning?`<div class="warning">${rich(b.warning)}</div>`:''}</section>${l.tenses.length?`<details class="table-detail"><summary>变位表</summary><select id="lessonVerb" aria-label="动词">${verbOptions('hablar')}</select><div id="lessonTables">${l.tenses.map(t=>table('hablar',t)).join('')}</div></details>`:''}<div class="reading-actions"><button class="secondary" data-section="${currentSection-1}" ${currentSection===0?'disabled':''}>上一节</button><button class="primary" ${currentSection===l.blocks.length-1?`data-complete="${id}"`:`data-section="${currentSection+1}"`}>${currentSection===l.blocks.length-1?'开始练习':'继续'} →</button></div></article>`;window.scrollTo(0,0)}
function verbOptions(v){return Object.keys(VERBS).map(x=>`<option value="${x}" ${x===v?'selected':''}>${x} · ${VERBS[x].meaning}</option>`).join('')}
function table(v,t){return `<h3>${TENSES[t]}</h3><div class="table-wrap"><table><tbody>${forms(v,t).map((a,i)=>`<tr><th>${PEOPLE[i]}</th><td>${rich(a)}</td></tr>`).join('')}</tbody></table></div>`}
function lab(){return `${header('变位')}<div class="controls"><select id="labVerb" aria-label="动词">${verbOptions('tener')}</select><select id="labTense" aria-label="时态">${Object.keys(TENSES).map(t=>`<option value="${t}">${TENSES[t]}</option>`).join('')}</select><button class="primary" id="labTrain">练习</button></div><section class="card" id="labTable">${table('tener','present')}</section><div class="card" id="nonfinite">${nonfinite('tener')}</div>`}
function nonfinite(v){return `<div class="forms-row"><span>原形<br><b>${rich(v)}</b></span><span>副动词<br><b>${rich(gerund(v))}</b></span><span>过去分词<br><b>${rich(participle(v))}</b></span></div>`}
function review(){const w=wrong(),d=due();return `${header('复习')}<div class="review-grid"><button class="review-card" data-session="due" ${d.length?'':'disabled'}><span>↺</span><h2>到期复习</h2><b>${d.length}</b></button><button class="review-card" data-session="wrong" ${w.length?'':'disabled'}><span>✎</span><h2>错题</h2><b>${w.length}</b></button><button class="review-card" data-session="mixed"><span>⤨</span><h2>混合练习</h2><small>已学课程</small></button></div>${w.length?`<h2 class="space">错题本</h2>${w.map(q=>`<details class="card"><summary>${esc(q.prompt)}</summary><p class="answer-line">${rich(q.answer.replaceAll('/',' / '))}</p><p>${rich(q.explain)}</p><button class="text-button" data-lesson="${q.lesson}">相关语法 →</button></details>`).join('')}`:'<div class="empty">暂无错题</div>'}`}
function map(){return `${header('知识索引',`${COVERAGE.length} 项`)}<div class="catalog">${COVERAGE.map(([name,id])=>`<button class="lesson-row" data-lesson="${id}"><span class="row-icon">${state.done[id]?'✓':'·'}</span><b>${name}</b><span>›</span></button>`).join('')}</div>`}
function shop(){return `${header('商店',`✦ ${balance()} XP`)}<p class="muted">新题 +2 · 到期复习 +1 · 首次满分题组 +5 · 每日最多 60 XP</p><div class="closet"><div class="avatar ${state.equipped.frame}">${pet()}</div><span>我的装扮</span></div>${[['theme','主题'],['pet','伙伴'],['frame','边框'],['hat','配饰'],['scene','课堂背景']].map(([kind,name])=>`<h2 class="space">${name}</h2><div class="shop-grid">${SHOP.filter(x=>x.kind===kind).map(x=>{const owned=state.owned.includes(x.id),active=state.equipped[kind]===x.id;return `<article class="shop-item ${active?'equipped':''}"><div class="item-preview ${kind==='theme'?'swatch '+x.id:kind==='frame'?'frame-preview '+x.id:''}">${kind==='pet'?mascot('idle',x.id):x.icon}</div><h3>${x.name}</h3><button class="${owned?'secondary':'primary'}" data-item="${x.id}" ${active||(!owned&&balance()<x.price)?'disabled':''}>${active?'使用中':owned?'使用':`✦ ${x.price}`}</button></article>`}).join('')}</div>`).join('')}`}
function buy(id){const item=SHOP.find(x=>x.id===id);if(!item)return false;if(!state.owned.includes(id)){if(balance()<item.price){toast('经验值不足');return false}state.spent+=item.price;state.owned.push(id)}state.equipped[item.kind]=id;save();if(view==='shop')render();toast('已装备 '+item.name);return true}
function settings(){return `${header('设置')}<div class="card settings-list"><label class="toggle">悬停释义<input id="dictionaryToggle" type="checkbox" ${state.dictionary?'checked':''}></label><a href="https://www.eudic.net/v4/es/app/plugins" target="_blank" rel="noopener noreferrer">西语助手官方插件 ↗</a><small class="muted">内置词义 · 西语助手查词链接</small></div><div class="card settings-list"><button class="secondary" id="export">导出进度</button><button class="secondary" id="import">导入进度</button><small class="muted">本机保存。换浏览器前请备份。</small></div><details class="card"><summary>参考资料</summary>${SOURCES.map(([t,u])=>`<p><a href="${u}" target="_blank" rel="noopener noreferrer">${t} ↗</a></p>`).join('')}<p><a href="https://www.rae.es/diccionario-estudiante/docs/numerales.pdf" target="_blank" rel="noopener noreferrer">RAE：数词 ↗</a></p></details>`}
function startLesson(id){const l=lessonById(id),round=state.rounds[id]||0,set=round%4;state.rounds[id]=round+1;save();start(PRACTICE_SETS[id][set],l.title+' · 第 '+(set+1)+' 套',id);session.set=set}
function start(qs,title,lesson=null){hideTip();if(!qs.length){toast('暂无题目，请先学习一课');return}view='quiz';session={qs:shuffle(qs),index:0,correct:0,title,lesson,checked:false,selected:null,results:[],earned:0,finished:false};drawQuiz();window.scrollTo(0,0)}
function drawQuiz(){const s=session,q=s.qs[s.index];if(!q){finish();return}s.checked=false;s.selected=null;$('#app').innerHTML=`<div class="quiz fade"><div class="lesson-top"><button class="icon-button" id="quitQuiz" aria-label="退出练习">×</button><div class="bar"><span style="width:${s.index/s.qs.length*100}%"></span></div><span>${s.index+1}/${s.qs.length}</span></div><small class="lesson-label">${esc(s.title)}</small><div class="quiz-companion">${mascot('thinking')}<span class="combo">${s.correct?'✦ '+s.correct:''}</span></div><div class="question">${rich(q.prompt)}</div>${q.options?`<div class="options">${shuffle(q.options).map((o,i)=>`<button class="option" data-option="${esc(o)}"><span class="option-number">${i+1}</span><span>${rich(o)}</span></button>`).join('')}</div>`:`<input class="answer-input" id="answer" aria-label="答案" placeholder="输入答案" autocomplete="off" autocapitalize="off" spellcheck="false"><div class="keyboard">${'á é í ó ú ü ñ'.split(' ').map(c=>`<button data-char="${c}" aria-label="输入 ${c}">${c}</button>`).join('')}</div>`}<div id="feedback" aria-live="polite"></div><div class="quiz-actions"><button class="text-button" id="reveal">暂时不会</button><button class="primary" id="check">检查</button></div></div>`;if(window.innerWidth>700)$('#answer')?.focus()}
function check(reveal=false){const s=session;if(!s||s.checked)return;const q=s.qs[s.index],a=q.options?s.selected:$('#answer').value;if(!reveal&&!a?.trim()){toast('请作答');return}hideTip();s.checked=true;const ok=!reveal&&correct(a,q.answer);if(ok)s.correct++;s.results.push({q,ok,a:a||'—'});const old=state.records[q.id]||{attempts:0,streak:0},streak=ok?old.streak+1:0,gain=grantXP(ok?(old.attempts===0?2:old.due<=Date.now()&&old.lastReward!==today()?1:0):0);state.records[q.id]={attempts:old.attempts+1,streak,wrong:!ok,lastReward:gain?today():old.lastReward,due:Date.now()+(ok?[1,3,7,14,30][Math.min(streak-1,4)]*86400000:600000)};s.earned+=gain;state.daily[today()]=(state.daily[today()]||0)+1;save();$('#feedback').innerHTML=`<div class="feedback ${ok?'':'wrong'}"><h3>${ok?'✓ 正确':'正确答案'}</h3>${ok?'':`<p class="answer-line">${rich(q.answer.replaceAll('/',' / '))}</p>`}<p>${rich(q.explain)}</p>${gain?`<span class="reward">+${gain} XP</span>`:''}</div>`;document.querySelectorAll('.option,#answer,.keyboard button').forEach(el=>el.disabled=true);$('#check').id='next';$('#next').textContent=s.index===s.qs.length-1?'完成':'继续';$('#reveal').hidden=true;$('#next').focus();celebrate(ok?'happy':'oops')}
function finish(){const s=session;if(!s)return;const score=Math.round(s.correct/s.qs.length*100),pass=score>=80;if(!s.finished){if(s.lesson&&pass)state.done[s.lesson]=true;const win=s.lesson+'-'+s.set;if(s.lesson&&s.set!==undefined&&score===100&&!state.setWins[win]){state.setWins[win]=true;s.earned+=grantXP(5)}save();s.finished=true}$('#app').innerHTML=`<div class="quiz"><div class="result-card"><div class="avatar ${state.equipped.frame}">${pet()}</div><h1>${pass?'完成！':'再练一次'}</h1><div class="result-stats"><div><b>${score}%</b><small>正确率</small></div><div><b>+${s.earned}</b><small>XP</small></div></div><p>${s.correct} / ${s.qs.length}${s.lesson&&!pass?' · 80% 通过':''}</p><button class="primary" data-view="home">继续学习</button><button class="text-button" id="retry">再练一轮</button></div>${s.results.filter(r=>!r.ok).map(r=>`<div class="card"><p>${rich(r.q.prompt)}</p><p class="answer-line">${rich(r.q.answer)}</p><p>${rich(r.q.explain)}</p><button class="text-button" data-lesson="${r.q.lesson}">语法 →</button></div>`).join('')}</div>`}
function exportProgress(){const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='Camino-进度-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已导出')}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.view)return go(b.dataset.view);if(b.dataset.lesson)return showLesson(b.dataset.lesson);if(b.dataset.practice)return startLesson(b.dataset.practice);if(b.dataset.complete){state.read[b.dataset.complete]=true;save();return startLesson(b.dataset.complete)}if(b.dataset.section!==undefined)return showLesson(currentLesson,Number(b.dataset.section));if(b.dataset.filter){filter=b.dataset.filter;return render()}if(b.dataset.item)return buy(b.dataset.item);if(b.dataset.option){if(session?.checked)return;session.selected=b.dataset.option;document.querySelectorAll('.option').forEach(o=>o.classList.toggle('selected',o===b));return}if(b.dataset.char){const a=$('#answer');if(a&&!a.disabled){const i=a.selectionStart,j=a.selectionEnd;a.value=a.value.slice(0,i)+b.dataset.char+a.value.slice(j);a.focus();a.setSelectionRange(i+1,i+1)}return}if(b.dataset.session){const mode=b.dataset.session,qs=mode==='due'?due():mode==='wrong'?wrong():BANK.filter(q=>state.read[q.lesson]||state.done[q.lesson]||state.records[q.id]);return start(shuffle(qs).slice(0,10),mode==='due'?'到期复习':mode==='wrong'?'错题':'混合练习')}switch(b.id){case'check':check();break;case'reveal':check(true);break;case'next':session.index++;drawQuiz();break;case'quitQuiz':go('review');break;case'retry':{const s=session;s.lesson?startLesson(s.lesson):start(s.qs,s.title);break}case'export':exportProgress();break;case'import':$('#file').click();break;case'labTrain':{const v=$('#labVerb').value,t=$('#labTense').value,l=LESSONS.find(l=>l.id!=='start'&&l.tenses.includes(t));start(BANK.filter(q=>q.id.startsWith(`${l.id}-${t}-${v}-`)),`${v} · ${TENSES[t]}`);break}}});
document.addEventListener('input',e=>{if(e.target.id==='search'){search=e.target.value;$('#results').innerHTML=results()}});
document.addEventListener('change',e=>{if(['labVerb','labTense'].includes(e.target.id)){const v=$('#labVerb').value;$('#labTable').innerHTML=table(v,$('#labTense').value);$('#nonfinite').innerHTML=nonfinite(v)}if(e.target.id==='lessonVerb')$('#lessonTables').innerHTML=lessonById(currentLesson).tenses.map(t=>table(e.target.value,t)).join('');if(e.target.id==='sectionSelect')showLesson(currentLesson,Number(e.target.value));if(e.target.id==='dictionaryToggle'){state.dictionary=e.target.checked;hideTip();save()}});
document.addEventListener('keydown',e=>{if(e.key==='Escape')hideTip();if(e.key==='Enter'&&view==='quiz'&&session&&!e.target.closest('button,a,.word,select')){if($('#next'))$('#next').click();else if($('#check'))check()}});
$('#file').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>5000000)throw Error();const s=JSON.parse(await f.text());if(!validBackup(s))throw Error();if(!confirm('用备份替换当前进度和装扮？'))return;state=migrate(s);save();go('home');toast('已恢复')}catch(e){toast('备份格式不正确，未修改进度')}finally{$('#file').value=''}});
document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();go('home')});
let tipTimer,tipClose,tipWord,tipPinned=false;
function hideTip(){tipPinned=false;clearTimeout(tipTimer);clearTimeout(tipClose);$('#wordTip').hidden=true;tipWord=null}
function showTip(el){if(!state.dictionary||!el?.isConnected)return;const word=el.dataset.word,entry=lookup(word),context=wordContext(el),note=contextMeaning(word,context);tipWord=el;const tip=$('#wordTip');tip.innerHTML=`<div class="tip-head"><b>${esc(word)}</b><button class="tip-close" aria-label="关闭释义">×</button></div>${entry?`<p>${esc(entry)}</p><small>词义</small>`:'<small>待补充词义</small>'}${note?`<div class="context-note"><b>句中用法</b><p>${esc(note)}</p></div>`:''}<button class="secondary add-word" data-add-word="${esc(word)}">${state.vocab[word.toLowerCase()]?'✓ 已收录':'＋ 生词本'}</button><a href="https://www.esdict.cn/dicts/es/${encodeURIComponent(word.toLowerCase())}" target="_blank" rel="noopener noreferrer">西语助手查词 ↗</a>`;tip.hidden=false;const r=el.getBoundingClientRect(),w=Math.min(300,window.innerWidth-24);tip.style.width=w+'px';tip.style.left=Math.max(12,Math.min(r.left,window.innerWidth-w-12))+'px';const h=tip.offsetHeight;tip.style.top=(r.bottom+h+14<window.innerHeight?r.bottom+9:Math.max(10,r.top-h-9))+'px'}
document.addEventListener('pointerover',e=>{const w=e.target.closest('.word');if(w&&state.dictionary){clearTimeout(tipClose);if(w!==tipWord){clearTimeout(tipTimer);tipTimer=setTimeout(()=>showTip(w),350)}}if(e.target.closest('#wordTip'))clearTimeout(tipClose)});
document.addEventListener('pointerout',e=>{if(tipPinned)return;if(e.target.closest('.word')||e.target.closest('#wordTip')){clearTimeout(tipTimer);clearTimeout(tipClose);tipClose=setTimeout(hideTip,220)}});
document.addEventListener('focusin',e=>{if(e.target.matches('.word'))showTip(e.target)});
document.addEventListener('click',e=>{if(e.target.closest('.tip-close'))hideTip();else if(e.target.closest('.word')&&!e.target.closest('button')){showTip(e.target.closest('.word'));tipPinned=true} else if(!e.target.closest('#wordTip'))hideTip()});
document.addEventListener('scroll',hideTip,{passive:true,capture:true});
function validV3(s){
  const obj=x=>x&&typeof x==='object'&&!Array.isArray(x),num=x=>Number.isSafeInteger(x)&&x>=0;
  if(!['vocab','rounds','setWins','rewardDays'].every(k=>obj(s[k])))return false;
  if(Object.keys(s.vocab).length>10000)return false;
  if(!Object.entries(s.vocab).every(([k,w])=>/^[a-záéíóúüñ]{1,60}$/i.test(k)&&obj(w)&&w.word===k&&typeof w.meaning==='string'&&w.meaning.length<=2000&&typeof w.context==='string'&&w.context.length<=1500&&typeof w.note==='string'&&w.note.length<=2000&&num(w.stage)&&w.stage<=5&&num(w.reviews)&&Number.isFinite(w.due)&&w.due>=0&&Number.isFinite(w.added)&&w.added>=0))return false;
  return Object.entries(s.rounds).every(([k,v])=>lessonById(k)&&num(v))&&Object.entries(s.setWins).every(([k,v])=>v===true&&LESSONS.some(l=>[0,1,2,3].some(i=>k===l.id+'-'+i)))&&Object.entries(s.rewardDays).every(([k,v])=>/^\d{4}-\d{1,2}-\d{1,2}$/.test(k)&&num(v)&&v<=60)&&['hat','scene'].every(k=>!s.equipped[k]||SHOP.some(x=>x.id===s.equipped[k]&&x.kind===k&&s.owned.includes(x.id)));
}
function grantXP(n){const d=today(),gain=Math.max(0,Math.min(n,60-(state.rewardDays[d]||0)));state.rewardDays[d]=(state.rewardDays[d]||0)+gain;state.xp+=gain;return gain}
function mascot(mood='idle',id=state.equipped.pet){
 const eye=(x,y,r=4)=>`<g class="animal-eye"><ellipse cx="${x}" cy="${y}" rx="${r}" ry="${r+1}" fill="#293e46"/><circle cx="${x+1.2}" cy="${y-1.7}" r="1.4" fill="#fff"/></g>`;
 const cheek=(x,y)=>`<ellipse cx="${x}" cy="${y}" rx="7" ry="3.5" fill="#efb1aa" opacity=".8"/>`;
 const smile=(x,y)=>`<path class="animal-smile" d="M${x-6} ${y}q6 7 12 0" fill="none" stroke="#3c4447" stroke-width="2.4" stroke-linecap="round"/>`;
 const face=(x=90,y=66)=>`${eye(x-17,y)}${eye(x+17,y)}${cheek(x-26,y+13)}${cheek(x+26,y+13)}${smile(x,y+14)}`;
 const art={
 sprout:`<g class="animal-ears"><path d="M65 55C46 34 43 1 57 3c15 1 18 35 18 48M101 48C102 19 115-4 126 5c12 12-5 41-15 52" fill="#f7efde" stroke="#d8c9ae" stroke-width="2"/><path d="M61 13q-2 20 8 32M120 14q-3 18-13 32" stroke="#f0b5b2" stroke-width="8" stroke-linecap="round"/></g><ellipse cx="90" cy="121" rx="35" ry="36" fill="#eadfc8"/><ellipse cx="91" cy="119" rx="25" ry="29" fill="#fff7e7"/><ellipse cx="65" cy="150" rx="21" ry="10" fill="#f7efde"/><ellipse cx="115" cy="150" rx="21" ry="10" fill="#f7efde"/><ellipse cx="90" cy="74" rx="44" ry="39" fill="#fff7e7"/>${face(90,71)}<path d="m86 83 4 4 4-4" fill="#d48b91"/><g class="animal-paw"><path d="M59 105q-14 18-2 26" stroke="#f7efde" stroke-width="15" stroke-linecap="round"/></g><path d="M118 107q17 12 6 25" stroke="#f7efde" stroke-width="14" stroke-linecap="round"/><g transform="rotate(-15 93 129)"><path d="m84 111 17 4-12 35Z" fill="#f2a14a"/><path d="m90 114-8-16m9 16 6-18" stroke="#7fa860" stroke-width="5" stroke-linecap="round"/></g>`,
 fox:`<g class="animal-tail"><path d="M111 136q62 0 47-65-32 16-47 45" fill="#da7845"/><path d="M158 71q10 26 1 44l-16-14Z" fill="#fff0d4"/></g><ellipse cx="86" cy="122" rx="32" ry="31" fill="#e98a4e"/><ellipse cx="86" cy="123" rx="19" ry="26" fill="#fff0d4"/><path d="m44 58-1-46 39 24m13 0 42-24-4 49" fill="#d87442"/><path d="m51 25 6 28 18-11m25 0 25-17-6 31" fill="#784b49"/><path d="M43 55Q84 22 135 55L128 83Q90 117 49 82Z" fill="#ed9853"/><path d="M45 62q22 7 43 27 21-23 45-27l-9 26q-37 35-69-2Z" fill="#fff3db"/>${eye(69,62)}${eye(108,62)}<path d="m82 85 8 8 8-8q-8-6-16 0" fill="#35434b"/>${smile(90,96)}${cheek(61,77)}${cheek(117,77)}<path d="M65 142v10M106 142v10" stroke="#744c45" stroke-width="15" stroke-linecap="round"/><path class="animal-paw" d="M57 111q-14-7-13 8" stroke="#d77b48" stroke-width="13" stroke-linecap="round"/>`,
 cactus:`<path d="M57 141 40 149M120 141l17 8" stroke="#77ae84" stroke-width="18" stroke-linecap="round"/><ellipse cx="90" cy="116" rx="48" ry="35" fill="#659c78" stroke="#447c60" stroke-width="4"/><path d="m90 87 21 14v24l-22 14-22-14v-24Z" fill="#a0bf70" stroke="#487c60" stroke-width="3"/><path d="m68 102-19-3m63 3 18-3m-42 40v12m-21-27-20 13m65-13 20 13" stroke="#487c60" stroke-width="3"/><ellipse cx="91" cy="66" rx="33" ry="32" fill="#a6cf92"/>${face(91,62)}<path class="animal-paw" d="M54 116q-17-25-25-13" stroke="#97c58d" stroke-width="17" stroke-linecap="round"/><path d="M128 115q16-13 21-5" stroke="#97c58d" stroke-width="16" stroke-linecap="round"/><path d="M76 37q12-17 28 0" fill="#79b985"/>`,
 owl:`<path d="m52 50-5-35 35 17m18 0 34-17-4 38" fill="#9175aa"/><ellipse cx="91" cy="91" rx="48" ry="60" fill="#a18ab9"/><ellipse cx="91" cy="113" rx="33" ry="31" fill="#e1d3e6"/><g stroke="#bba4c5" stroke-width="3" fill="none"><path d="m69 108 5 5 5-5m10 0 5 5 5-5m-26 16 5 5 5-5m10 0 5 5 5-5"/></g><ellipse cx="71" cy="66" rx="24" ry="27" fill="#fff1d9"/><ellipse cx="111" cy="66" rx="24" ry="27" fill="#fff1d9"/>${eye(72,67,6)}${eye(111,67,6)}<path d="m84 80 7 12 7-12Z" fill="#dda358"/><path class="animal-paw" d="M47 88q-29 28-6 41l13-31" fill="#82649c"/><path d="M135 87q25 32 2 44l-12-34" fill="#82649c"/><path d="m71 147-6 7m6-7 5 7m35-7-5 7m5-7 6 7" stroke="#c99c5c" stroke-width="5" stroke-linecap="round"/>`,
 axolotl:`<g class="animal-ears" stroke="#df86a5" stroke-width="8" stroke-linecap="round"><path d="M54 52 31 31M49 65 23 60M51 79 27 92M127 52l23-21m-19 34 27-5m-27 19 23 13"/></g><path class="animal-tail" d="M119 130q37-19 36 11-30 21-48 6" fill="#e4a1ba"/><ellipse cx="89" cy="122" rx="31" ry="31" fill="#f1bdce"/><ellipse cx="89" cy="126" rx="20" ry="23" fill="#ffe1e8"/><rect x="46" y="35" width="88" height="66" rx="31" fill="#f5c7d5"/>${face(90,61)}<path class="animal-paw" d="M62 115q-25 0-23 12" stroke="#edafc3" stroke-width="14" stroke-linecap="round"/><path d="m70 147-11 5m44-5 12 5" stroke="#edafc3" stroke-width="14" stroke-linecap="round"/>`,
 penguin:`<ellipse cx="68" cy="151" rx="21" ry="9" fill="#e9b557"/><ellipse cx="116" cy="151" rx="21" ry="9" fill="#e9b557"/><path class="animal-paw" d="M51 84Q24 90 29 126l24-17" fill="#436b83"/><path d="M130 85q27 10 19 42l-21-19" fill="#436b83"/><path d="M45 99q-2-67 45-69 50 1 50 69v14q-4 38-50 38-45 0-45-42Z" fill="#4e7c92"/><path d="M56 90q-4-50 22-44l12 17 14-17q25-6 23 44l3 20q-1 32-40 32-39 0-38-32Z" fill="#fff4dc"/>${eye(73,73)}${eye(108,73)}<path d="m80 84 10 10 11-10q-11-7-21 0" fill="#e4a445"/>${cheek(62,87)}${cheek(120,87)}<path d="M53 104q39 12 76-1" stroke="#cb776c" stroke-width="11"/><path d="m112 106-3 26" stroke="#cb776c" stroke-width="12"/><path d="M79 32q-4-18 13-12l4 10" fill="#4e7c92"/>`,
 dragon:`<path class="animal-tail" d="M111 137q47 13 46-33-15 16-36 10" fill="#97a587"/><g class="animal-ears"><path d="m51 83-33-31 4 48 35 16m70-33 30-31-2 49-32 14" fill="#d5b39a" stroke="#a88675" stroke-width="3"/></g><ellipse cx="90" cy="121" rx="34" ry="34" fill="#a4b694"/><ellipse cx="90" cy="125" rx="21" ry="26" fill="#f0ddb1"/><path d="m61 46-7-26 20 17m32 0 17-19-3 29" fill="#e7c17d"/><rect x="48" y="39" width="84" height="66" rx="30" fill="#b6c6a6"/>${eye(71,62)}${eye(111,62)}<ellipse cx="91" cy="84" rx="31" ry="18" fill="#cad6b9"/><circle cx="80" cy="80" r="2.5" fill="#708472"/><circle cx="103" cy="80" r="2.5" fill="#708472"/>${smile(91,92)}<path class="animal-paw" d="M57 113 44 120" stroke="#9fb28b" stroke-width="15" stroke-linecap="round"/><path d="m72 146-11 8m47-8 10 8" stroke="#9fb28b" stroke-width="16" stroke-linecap="round"/>`,
 cloud:`<path class="animal-tail" d="M125 127q30-5 37 10l-18 10 19 8q-28 20-45-5" fill="#a8c8d3"/><path d="M46 94Q47 37 85 40q40 0 46 52l10 35q-9 28-55 24-45 1-40-57" fill="#cee2e6"/><ellipse cx="84" cy="99" rx="28" ry="35" fill="#eaf5f1"/>${eye(65,65)}${eye(102,65)}<ellipse cx="83" cy="82" rx="20" ry="12" fill="#f7f9ee"/><path d="m78 76 6 6 6-6Z" fill="#536973"/><path d="m49 79-19-4m20 11-20 4m85-11 20-4m-20 11 20 4" stroke="#7f9fa8" stroke-width="2"/>${smile(84,89)}<path class="animal-paw" d="M55 111q-26 0-27 18 24 8 36-8" fill="#aacbd5"/><path d="M101 122q10 23 32 16l-22-22" fill="#aacbd5"/>`,
 cat:`<path class="animal-tail" d="M119 137q40 5 25-38" stroke="#dba45f" stroke-width="15" fill="none" stroke-linecap="round"/><ellipse cx="89" cy="122" rx="33" ry="33" fill="#edc88f"/><ellipse cx="89" cy="125" rx="21" ry="25" fill="#fff0d1"/><path d="M46 58 45 17l35 25m21-1 34-24-2 43" fill="#eac080"/><path d="m52 28 5 26 19-9m29 0 22-17-5 27" fill="#e9a69e"/><ellipse cx="90" cy="72" rx="44" ry="34" fill="#f2d29a"/><path d="m80 40 4 11m8-12v13m9-11-4 10" stroke="#dba45f" stroke-width="4" stroke-linecap="round"/>${eye(72,65)}${eye(108,65)}<path d="m85 76 5 5 5-5Z" fill="#c98282"/><path d="M90 81q-3 10-11 4m11-4q3 10 11 4M53 78l-25-3m25 9-25 4m99-10 25-3m-25 9 25 4" stroke="#9f805e" stroke-width="2" fill="none"/><path class="animal-paw" d="M63 116q-15-11-21 0" stroke="#e8bc7b" stroke-width="13" stroke-linecap="round"/><path d="M69 147v7m42-7v7" stroke="#e8bc7b" stroke-width="16" stroke-linecap="round"/>`,
 whale:`<path class="animal-tail" d="M134 113q17-20 29-14l-2 15 13-2q-2 30-39 31" fill="#659fb9"/><path d="M21 104q-1-45 52-45 55 0 66 45l7 30q-21 25-68 20-57-2-57-50Z" fill="#83b9d1"/><path d="M25 119q49 22 111 0l7 17q-21 24-68 18-34-1-50-35" fill="#d9e9e8"/>${eye(53,102)}${eye(98,102)}${cheek(40,115)}${cheek(111,115)}${smile(75,119)}<path class="animal-paw" d="M79 132q-3 26 19 26l9-19" fill="#609bb8"/><g class="animal-ears" fill="none" stroke="#a3dce5" stroke-width="6" stroke-linecap="round"><path d="M74 59V29q-13-21-25-7m25 19q18-28 31-15"/></g><ellipse cx="46" cy="29" rx="4" ry="6" fill="#a3dce5"/><ellipse cx="109" cy="32" rx="4" ry="6" fill="#a3dce5"/>`,
 mushroom:`<ellipse cx="90" cy="120" rx="40" ry="35" fill="#f5f2e7"/><ellipse cx="61" cy="142" rx="17" ry="19" fill="#50606b"/><ellipse cx="119" cy="142" rx="17" ry="19" fill="#50606b"/><circle cx="57" cy="38" r="18" fill="#50606b"/><circle cx="124" cy="38" r="18" fill="#50606b"/><ellipse cx="90" cy="70" rx="48" ry="38" fill="#fffdf1"/><ellipse cx="71" cy="64" rx="13" ry="17" transform="rotate(25 71 64)" fill="#61717a"/><ellipse cx="109" cy="64" rx="13" ry="17" transform="rotate(-25 109 64)" fill="#61717a"/>${eye(71,64,4)}${eye(109,64,4)}<path d="m84 79 6 6 6-6Z" fill="#435761"/>${smile(90,86)}${cheek(59,81)}${cheek(121,81)}<path class="animal-paw" d="M58 112q-22-11-19 6" stroke="#50606b" stroke-width="17" stroke-linecap="round"/><path d="m114 123 15-33" stroke="#77a96a" stroke-width="6"/><path d="M124 103q-15-19-17-5m19 1q19-15 21-2" stroke="#8cba73" stroke-width="5" fill="none"/>`,
 robot:`<path class="animal-tail" d="M118 131q27 0 21-21" fill="none" stroke="#b78e6b" stroke-width="14" stroke-linecap="round"/><ellipse cx="90" cy="122" rx="33" ry="33" fill="#d6b491"/><ellipse cx="90" cy="129" rx="21" ry="24" fill="#f8e7c8"/><path class="animal-ears" d="M52 41q-24-1-26 40 2 23 22 4l14-32m66-12q25-1 25 40-2 23-22 4l-12-32" fill="#9e765b"/><rect x="47" y="35" width="86" height="69" rx="30" fill="#dfbe98"/><path d="M72 36q-7 28 18 34 22-13 13-34" fill="#f7e8cd"/>${eye(70,64)}${eye(110,64)}<ellipse cx="90" cy="83" rx="22" ry="16" fill="#f7e8cd"/><path d="M82 76q8-5 16 0l-8 8Z" fill="#4a4b49"/><path d="M85 88v9q5 9 10 0v-9" fill="#e6959a"/><path d="M59 105q31 12 61 0" stroke="#80a6a3" stroke-width="8"/><circle cx="90" cy="114" r="6" fill="#e4bd68"/><path class="animal-paw" d="M61 118q-15-15-23-3" stroke="#cda680" stroke-width="15" stroke-linecap="round"/><path d="M69 146v8m43-8v8" stroke="#cda680" stroke-width="16" stroke-linecap="round"/>`
 };
 const hat=state.equipped.hat||'none',accessories={beret:'<path d="M56 35Q41 16 72 11q40-7 54 14L109 37Z" fill="#8f789f"/><path d="m88 15 4-9" stroke="#68527d" stroke-width="4"/>',bow:'<path d="m104 37 23-20 2 30-25-7-12 13-3-26Z" fill="#db8d9c"/><circle cx="105" cy="37" r="5" fill="#b7687d"/>',explorer:'<path d="M61 31V17q29-13 54 2v13M47 34h82" fill="#e6c28c" stroke="#ae895e" stroke-width="7"/><path d="M61 26h52" stroke="#79988a" stroke-width="6"/>',glasses:'<g stroke="#675b73" stroke-width="3" fill="none"><circle cx="73" cy="65" r="13"/><circle cx="109" cy="65" r="13"/><path d="M86 65h10"/></g>',crown:'<path d="m66 33-4-23 18 12 11-21 12 21 18-12-5 23Z" fill="#f0cd72" stroke="#cfa349" stroke-width="2"/><circle cx="91" cy="23" r="4" fill="#a5bbb1"/>'};
 return `<svg class="mascot animal mood-${mood} species-${id}" viewBox="0 0 180 170" role="img" aria-label="${esc(SHOP.find(x=>x.id===id)?.name||'小兔')}"><ellipse cx="91" cy="159" rx="52" ry="7" fill="#3e6057" opacity=".09"/><g class="animal-body">${art[id]||art.sprout}<g transform="translate(0 ${id==='whale'?30:0})">${accessories[hat]||''}</g></g></svg>`;
}

function celebrate(mood){document.querySelectorAll('.quiz-companion').forEach(el=>el.innerHTML=mascot(mood));if(mood==='happy'){const feedback=$('#feedback');if(feedback)feedback.insertAdjacentHTML('beforeend','<div class="spark-burst" aria-hidden="true">'+Array.from({length:7},(_,i)=>`<i style="--i:${i}">✦</i>`).join('')+'</div>')}}
function wordContext(el){const box=el?.closest('.example,.prose,.question,.feedback,.option,.vocab-example');if(!box)return '';const full=box.textContent||'';if(box.matches('.example,.question,.option'))return full.trim().slice(0,1500);const range=document.createRange();range.selectNodeContents(box);range.setEndBefore(el);const pos=range.toString().length;const left=full.slice(0,pos),right=full.slice(pos);const from=Math.max(left.lastIndexOf('。'),left.lastIndexOf('\n'),left.lastIndexOf('；'))+1,to=right.search(/[。\n；]/);return (left.slice(from)+right.slice(0,to<0?undefined:to+1)).trim().slice(0,1500)}
function contextMeaning(word,context){
 const w=word.toLowerCase(),c=context.toLowerCase().normalize('NFC');
 const phrases=[
 [/\b(no sé|pregunta|preguntó|no sabe) si\b/,['si'],'这里的 si 表示“是否”，引导间接一般疑问句，不表示假设条件。'],
 [/\bsi\b.*(vendría|viajaría|ayudaría|responderíamos)/,['si'],'这里的 si 表示“如果”，引出与条件式主句配合的假设条件。'],
 [/\b(quiero|deseo|espero|prefiero) que\b/,['que'],'这里的 que 引出所希望发生的事情；主从句主语不同时，从句通常用虚拟式。'],
 [/\b(dice|dijo|creo|sé) que\b/,['que'],'这里的 que 引出所说、所知或所认为的内容，相当于把后面的句子整体作为宾语。'],
 [/\b(libro|casa|fotos|coche) que\b/,['que'],'这里的 que 是关系代词，回指前面的名词，把后面的句子接过来说明“哪一本／哪一座／哪些”。'],
 [/\bllamarse|\b(me llamo|te llamas|se llama)\b/,['llamo','llamas','llama'],'这里 llamarse 表示“名字叫……”，不是打电话。'],
 [/\b(sopa|agua|puerta) est[áa]\b/,['está'],'这里 estar 描写事物当前的状态，例如温度或开关状态。'],
 [/\b(reunión|fiesta) es\b/,['es'],'这里 ser 与活动连用，说明活动举行的地点或时间。'],
 [/\bsoy|\bson\b|\bes\b/,['soy'],'soy 是 ser 的第一人称单数，常用于身份、来源等：我是……。'],
 [/\bcomo\b.*(pan|arroz|fruta)/,['como'],'这里 como 是 comer 的第一人称现在时：我吃；不是比较连接词“像”。'],
 [/\btan\b.*\bcomo\b/,['como'],'这里 como 引出同等比较的对象：和……一样。'],
 [/\bdesde hace\b/,['hace'],'desde hace + 时长：从多久以前起，持续到现在。'],
 [/\bsobre la mesa\b/,['sobre'],'这里 sobre 表示位置：在桌子上。'],
 [/\bhablamos sobre\b/,['sobre'],'这里 sobre 引出谈论的主题：关于……。'],
 [/\bpara (aprender|estudiar|trabajar)\b/,['para'],'这里 para + 原形说明目的：为了学习／工作。'],
 [/\bpara (ti|mí|ella|él)\b/,['para'],'这里 para 引出接受者：给你／我／她／他。'],
 [/\bpor (miedo|enfermedad)\b/,['por'],'这里 por 引出原因：由于恐惧／疾病。'],
 [/\bpor (el parque|la ventana)\b/,['por'],'这里 por 表示经过的路径：穿过公园／经由窗户。'],
 [/(tengo|tienes|tiene|tenemos|tenéis|tienen|tenía|tener) que/,['que','tengo','tienes','tiene','tenemos','tenéis','tienen','tenía','tener'],'tener que + 原形：必须、得做某事；这里的 que 是动词短语的连接成分。'],
 [/\bhay que\b/,['hay','que'],'hay que + 原形：有必要做某事，未指定执行者。'],
 [/\b(voy|vas|va|vamos|vais|van|iba|ir) a\b/,['voy','vas','va','vamos','vais','van','iba','ir','a'],'ir a + 原形：打算、即将做某事；若后接地点，则表示前往该地。'],
 [/\b(vuelvo|vuelve|volver|volvemos) a\b/,['vuelvo','vuelve','volver','volvemos','a'],'volver a + 原形：再次做某事，不是返回某个地点。'],
 [/\b(sigo|sigue|seguimos|siguen|seguir)\b/,['sigo','sigue','seguimos','siguen','seguir'],'seguir + 副动词：继续做、仍在做；后接地点或人时可表示跟随。'],
 [/\b(lleva|llevo|llevan|llevaba)\b.*(ando|iendo|小时|年|mes|hora)/,['lleva','llevo','llevan','llevaba'],'llevar + 时长 + 副动词：某动作已经持续多久，并且还在继续。'],
 [/\b(hace|hacen) falta\b/,['hace','hacen','falta'],'hacer falta：需要、缺少。所缺之物是主语，单数 hace，复数 hacen。'],
 [/\bse (lo|la|los|las)\b/,['se'],'se 在 se lo/la/los/las 中替代与格 le/les，表示“给他/她/他们/您”，不是“自己”。'],
 [/\bse (venden|alquilan|necesitan|reparan|entregaron)\b/,['se'],'这里是自复被动标记：某物被出售、出租、需要等；se 本身不译成“自己”。'],
 [/\bse (vive|come|busca a)\b/,['se'],'这里的 se 构成无人称表达，泛指“人们”，动词用第三人称单数。'],
 [/\b(se|me|te|nos|os) (arrepient|quej|acuerd|llam)/,['se','me','te','nos','os'],'这里的代词属于代词式动词结构，随主语变化，不能机械地都译为“自己”。'],
 [/\b(el uno al otro|mutuamente)\b/,['se','nos','os'],'此处表示相互关系：动作参与者彼此实施动作。'],
 [/\b(aunque)\b/,['aunque'],'aunque：虽然／即使。陈述式常呈现已知事实；虚拟式可表示假设或不影响结论的让步。'],
 [/\bcuando\b/,['cuando'],'cuando：当……时。习惯和既成事件常用陈述式；尚未发生的将来事件常用虚拟式。'],
 [/\bsi\b/,['si'],'不带重音的 si 可引导“如果”的条件从句，也可在 preguntar/no saber 后表示“是否”。sí 带重音才表示“是的”等。'],
 [/\bpor tanto\b/,['por','tanto'],'por tanto 是一个整体：因此、所以，引出结果。'],
 [/\bpor qué\b/,['por','qué'],'por qué：为什么；疑问结构中的 qué 带重音。porque 连写表示“因为”。'],
 [/\btan\b.*\bque\b/,['tan','que'],'tan + 形容词/副词 + que：如此……以至于……，que 引出结果。'],
 [/\btanto\b.*\bcomo\b/,['tanto','como'],'tanto … como：与……一样多／一样程度；como 引出比较对象。'],
 [/\bantes de\b/,['antes','de'],'antes de + 名词/原形：在……之前。'],
 [/\bal (salir|entrar|ver|terminar|oír)\b/,['al'],'al + 原形：当做某事时／一做某事就……；al 是 a + el 的合写。'],
 [/\blo que\b/,['lo','que'],'lo que：……的事情／所……的内容。lo 是中性形式，不对应某个阳性名词。'],
 [/\b(el|la|los|las) (mío|mía|míos|mías|tuyo|tuya|suyo|suya)/,['el','la','los','las'],'这里定冠词与重读物主词构成物主代词，代替前文提过的东西。'],
 [/\bde (madera|cristal|metal)\b/,['de'],'这里的 de 引出材质：木制的、玻璃制的、金属制的。'],
 [/\ben (autobús|bicicleta|tren|coche)\b/,['en'],'这里的 en 表示交通方式：乘……、骑……。'],
 [/\bpara\b/,['para'],'para 常引出目的、接受者、用途或截止时间；para + 原形表示“为了做……”。'],
 [/\bpor\b/,['por'],'por 可引出原因、途经之处、交换价格或方式。结合后面的成分理解，不能一律译成“为了”。'],
 [/\b(donde|dónde)\b/,['donde'],'donde 引导地点关系或地点从句，意为“……的地方”；疑问“哪里”写 dónde。'],
 [/\bdesde\b/,['desde'],'desde 标记时间或空间的起点：自从……／从……起。'],
 [/\b(habría|había|habían|he|has|ha|hemos|han)\b/,['he','has','ha','hemos','han','había','habían'],'haber 在这里若与过去分词连用，是完成时的助动词，不译为“拥有”。'],
 [/\bni\b/,['ni'],'ni：也不、既不……也不……，连接被否定的并列成分。'],
 [/\bque\b/,['que'],'que 的作用取决于结构：动词后可引出“……这件事”的宾语从句；名词后可连接修饰该名词的关系从句。']
 ];
 return phrases.find(([re,words])=>words.includes(w)&&re.test(c))?.[2]||'';
}
function updateWords(){const n=$('#wordCount');if(n)n.textContent=Object.keys(state.vocab).length;const dock=$('#wordDock');if(dock){dock.classList.toggle('has-due',vocabDue().length>0);dock.setAttribute('aria-label',`生词本：${Object.keys(state.vocab).length} 词，${vocabDue().length} 词待复习`)}document.body.dataset.scene=state.equipped.scene||'meadow'}
function vocabDue(){return Object.values(state.vocab).filter(w=>w.due<=Date.now()).sort((a,b)=>a.due-b.due)}
function openWord(word,context='',note=''){const k=word.trim().toLowerCase().normalize('NFC');if(!/^[a-záéíóúüñ]{1,60}$/i.test(k))return;const saved=state.vocab[k],meaning=saved?.meaning||lookup(k)||'';hideTip();const sheet=$('#wordSheet');sheet.hidden=false;sheet.innerHTML=`<div class="sheet-shade"></div><section class="word-sheet" role="dialog" aria-modal="true" aria-labelledby="wordSheetTitle"><button class="icon-button sheet-close" aria-label="关闭">×</button><h2 id="wordSheetTitle">${saved?'编辑':'收录'} · ${esc(k)}</h2><form id="wordForm"><input type="hidden" name="word" value="${esc(k)}"><label>词义<textarea name="meaning" maxlength="2000" required placeholder="填写词义">${esc(meaning)}</textarea></label><label>原句<textarea name="context" maxlength="1500">${esc(saved?.context||context)}</textarea></label><label>句中用法<textarea name="note" maxlength="2000">${esc(saved?.note||note)}</textarea></label><button class="primary" type="submit">${saved?'保存':'加入生词本'}</button></form></section>`;sheet.querySelector('textarea').focus()}
function closeWord(){const s=$('#wordSheet');s.hidden=true;s.innerHTML='';$('#wordDock').focus()}
function storeWord(word,meaning,context,note){const k=word.toLowerCase().normalize('NFC');if(!/^[a-záéíóúüñ]{1,60}$/i.test(k)||!meaning.trim())return false;const old=state.vocab[k];if(!old&&Object.keys(state.vocab).length>=10000)return false;state.vocab[k]={word:k,meaning:meaning.trim().slice(0,2000),context:context.slice(0,1500),note:note.slice(0,2000),stage:old?.stage||0,reviews:old?.reviews||0,due:old?.due??Date.now(),added:old?.added??Date.now(),lastReward:old?.lastReward||''};save();updateWords();return true}
function collectWord(word,context,note){const k=word.toLowerCase().normalize('NFC');if(state.vocab[k]){toast('已在生词本');return}const meaning=lookup(k);if(!meaning){openWord(k,context,note);return}if(!storeWord(k,meaning,context,note))return;$('#wordDock').classList.remove('caught');void $('#wordDock').offsetWidth;$('#wordDock').classList.add('caught');toast('＋ '+k)}
let wordSearch='',wordMode='all',wordReview=null,removedWord=null;
function vocabulary(){updateWords();return `${header('生词本',Object.keys(state.vocab).length+' 词')}${removedWord?'<button class="text-button" id="undoWord">撤销移除</button>':''}<div class="vocab-hero">${mascot('teach')}<div><h2>${vocabDue().length} 词待复习</h2><button class="primary" id="reviewWords" ${vocabDue().length?'':'disabled'}>今日复习 →</button></div></div><div class="vocab-toolbar"><input class="search" id="wordSearch" placeholder="搜索单词或词义" aria-label="搜索生词" value="${esc(wordSearch)}"><button class="secondary" id="newWord">＋ 添加</button></div><div class="chips"><button class="chip ${wordMode==='all'?'active':''}" data-word-mode="all">全部</button><button class="chip ${wordMode==='due'?'active':''}" data-word-mode="due">待复习</button><button class="chip ${wordMode==='learned'?'active':''}" data-word-mode="learned">熟悉</button></div><div id="wordList">${wordRows()}</div>`}
function wordRows(){const ws=Object.values(state.vocab).filter(w=>(wordMode==='all'||(wordMode==='due'?w.due<=Date.now():w.stage>=4))&&(w.word+' '+w.meaning).toLowerCase().includes(wordSearch.toLowerCase())).sort((a,b)=>b.added-a.added);return ws.map(w=>`<article class="vocab-card"><div class="vocab-title"><h2>${esc(w.word)}</h2><small>${w.due<=Date.now()?'待复习':new Date(w.due).toLocaleDateString('zh-CN')+' 复习'} · ${w.stage}/5</small></div><p>${esc(w.meaning)}</p>${w.context?`<p class="vocab-example">${rich(w.context)}</p>`:''}${w.note?`<p class="context-note">${esc(w.note)}</p>`:''}<button class="text-button" data-edit-word="${esc(w.word)}">编辑</button><button class="text-button" data-delete-word="${esc(w.word)}">移除</button></article>`).join('')||'<div class="empty">拖拽单词到右下角，或点按单词收录。</div>'}
function beginWords(){const words=vocabDue().slice(0,20).map(w=>w.word);if(!words.length){toast('今日复习已完成');return}wordReview={words,index:0,revealed:false,earned:0};view='wordReview';session=null;hideTip();drawWordReview()}
function drawWordReview(){const r=wordReview;if(!r)return;const w=state.vocab[r.words[r.index]];if(!w){$('#app').innerHTML=`<section class="result-card">${mascot('happy')}<h1>今日完成</h1><p>${r.words.length} 词 · +${r.earned} XP</p><button class="primary" data-view="vocabulary">生词本</button><button class="text-button" id="reviewWords" ${vocabDue().length?'':'disabled'}>继续复习</button></section>`;return}r.revealed=false;$('#app').innerHTML=`<div class="word-review"><div class="lesson-top"><button class="icon-button" data-view="vocabulary" aria-label="退出生词复习">×</button><div class="bar"><span style="width:${r.index/r.words.length*100}%"></span></div><span>${r.index+1}/${r.words.length}</span></div><div class="flashcard">${mascot('thinking')}<h1>${esc(w.word)}</h1><div id="wordAnswer" hidden><p>${esc(w.meaning)}</p>${w.context?`<p>${esc(w.context)}</p>`:''}${w.note?`<p class="context-note">${esc(w.note)}</p>`:''}</div></div><button class="primary" id="flipWord">查看词义</button><div class="word-ratings" id="wordRatings" hidden><button class="secondary" data-rate-word="0">忘了 · 10 分钟</button><button class="secondary" data-rate-word="1">模糊 · 1 天</button><button class="primary" data-rate-word="2">记住了</button></div></div>`}
function rateWord(grade){const r=wordReview;if(!r||!r.revealed)return;const w=state.vocab[r.words[r.index]];if(!w)return;r.revealed=false;w.reviews++;w.stage=grade===0?0:grade===1?Math.max(0,w.stage-1):Math.min(5,w.stage+1);const days=grade===0?0:grade===1?1:[1,1,3,7,14,30][w.stage];w.due=Date.now()+(grade===0?600000:days*86400000);if(grade===2&&w.lastReward!==today()){r.earned+=grantXP(1);w.lastReward=today()}save();updateWords();r.index++;drawWordReview()}
document.addEventListener('submit',e=>{if(e.target.id!=='wordForm')return;e.preventDefault();const f=new FormData(e.target);if(storeWord(f.get('word'),f.get('meaning'),f.get('context'),f.get('note'))){closeWord();toast('已保存');if(view==='vocabulary')render()}});
document.addEventListener('input',e=>{if(e.target.id==='wordSearch'){wordSearch=e.target.value;$('#wordList').innerHTML=wordRows()}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(e.target.closest('.sheet-shade'))return closeWord();if(!b||b.disabled)return;if(b.classList.contains('sheet-close'))return closeWord();if(b.dataset.addWord){const el=tipWord,context=wordContext(el);return collectWord(b.dataset.addWord,context,contextMeaning(b.dataset.addWord,context))}if(b.dataset.editWord)return openWord(b.dataset.editWord);if(b.dataset.deleteWord){const key=b.dataset.deleteWord,entry=state.vocab[key];removedWord=entry;delete state.vocab[key];save();render();toast('已移除 '+key);return}if(b.dataset.wordMode){wordMode=b.dataset.wordMode;return render()}if(b.dataset.rateWord!==undefined)return rateWord(+b.dataset.rateWord);if(b.id==='undoWord'&&removedWord){state.vocab[removedWord.word]=removedWord;removedWord=null;save();return render()}if(b.id==='wordDock'){updateWords();return go('vocabulary')}if(b.id==='reviewWords')return beginWords();if(b.id==='newWord'){const word=prompt('西班牙语单词');if(word)openWord(word);return}if(b.id==='flipWord'&&wordReview){wordReview.revealed=true;$('#wordAnswer').hidden=false;$('#wordRatings').hidden=false;b.hidden=true;$('.flashcard').classList.add('flipped')}});
let draggedWord=null,longWordTimer,longWordUsed=false;
document.addEventListener('dragstart',e=>{const el=e.target.closest('.word');if(!el)return;const word=el.dataset.word,context=wordContext(el);draggedWord={word,context,note:contextMeaning(word,context)};e.dataTransfer.setData('text/plain',word);e.dataTransfer.effectAllowed='copy';hideTip();$('#wordDock').classList.add('drop-ready');$('#wordDock').querySelector('span').textContent='拖到这里'});
document.addEventListener('dragend',()=>{draggedWord=null;$('#wordDock').classList.remove('drop-ready','drag-over');$('#wordDock').querySelector('span').textContent='生词本'});
$('#wordDock').addEventListener('dragover',e=>{if(!draggedWord)return;e.preventDefault();e.dataTransfer.dropEffect='copy';$('#wordDock').classList.add('drag-over')});
$('#wordDock').addEventListener('dragleave',()=>$('#wordDock').classList.remove('drag-over'));
$('#wordDock').addEventListener('drop',e=>{e.preventDefault();if(draggedWord)collectWord(draggedWord.word,draggedWord.context,draggedWord.note);$('#wordDock').classList.remove('drop-ready','drag-over');$('#wordDock').querySelector('span').textContent='生词本'});
document.addEventListener('pointerdown',e=>{const el=e.target.closest('.word');if(!el)return;longWordUsed=false;clearTimeout(longWordTimer);if(e.pointerType==='touch')longWordTimer=setTimeout(()=>{longWordUsed=true;showTip(el);tipPinned=true},450)});
document.addEventListener('pointerup',()=>clearTimeout(longWordTimer));document.addEventListener('pointermove',()=>clearTimeout(longWordTimer));document.addEventListener('pointercancel',()=>clearTimeout(longWordTimer));
document.addEventListener('click',e=>{if(longWordUsed){longWordUsed=false;e.preventDefault();e.stopImmediatePropagation()}},true);
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#wordSheet').hidden)closeWord();if(e.key==='Tab'&&!$('#wordSheet').hidden){const els=[...$('#wordSheet').querySelectorAll('button,input:not([type=hidden]),textarea')],first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
const originalUpdateHeader=updateHeader;updateHeader=function(){originalUpdateHeader();updateWords()};



let pointerDrag=null;
function endPointerDrag(){pointerDrag=null;document.querySelector('.word-ghost')?.remove();$('#wordDock').classList.remove('drop-ready','drag-over');$('#wordDock').querySelector('span').textContent='生词本'}
document.addEventListener('pointerdown',e=>{const el=e.target.closest('.word');if(el&&e.pointerType!=='touch'&&e.button===0)pointerDrag={el,x:e.clientX,y:e.clientY,active:false}});
document.addEventListener('pointermove',e=>{const d=pointerDrag;if(!d)return;if(!d.active&&Math.hypot(e.clientX-d.x,e.clientY-d.y)>7){d.active=true;hideTip();const ghost=document.createElement('span');ghost.className='word-ghost';ghost.textContent=d.el.dataset.word;document.body.append(ghost);$('#wordDock').classList.add('drop-ready');$('#wordDock').querySelector('span').textContent='拖到这里'}if(d.active){e.preventDefault();const ghost=document.querySelector('.word-ghost');ghost.style.left=e.clientX+12+'px';ghost.style.top=e.clientY-20+'px';const r=$('#wordDock').getBoundingClientRect();$('#wordDock').classList.toggle('drag-over',e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom)}});
document.addEventListener('pointerup',e=>{const d=pointerDrag;if(d?.active){longWordUsed=true;const r=$('#wordDock').getBoundingClientRect();if(e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom){const context=wordContext(d.el);collectWord(d.el.dataset.word,context,contextMeaning(d.el.dataset.word,context))}}endPointerDrag()});
document.addEventListener('pointercancel',endPointerDrag);

go('home');
